wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1661965517.729991
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 53
      - 54
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.8.8
      5: 0.13.1
      8:
      - 1
      - 3
      - 5
anneal_gamma:
  desc: null
  value: null
batch_size:
  desc: null
  value: 50
burnin_epochs:
  desc: null
  value: 250
component:
  desc: null
  value: null
criterion_name:
  desc: null
  value: MSELoss
cutoff_percentile:
  desc: null
  value: null
input_dim:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: SGLD_2_outputs
noise_multiplier:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 1000
num_layers:
  desc: null
  value: 4
num_networks:
  desc: null
  value: 150
num_units:
  desc: null
  value: 50
optimiser_name:
  desc: null
  value: Adam
output_dim:
  desc: null
  value: 2
seed:
  desc: null
  value: 1234
sortby:
  desc: null
  value: null
val_split:
  desc: null
  value: null
weight_decay:
  desc: null
  value: null
x_cols:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
y_cols:
  desc: null
  value:
  - 6
  - 7
