wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1661967276.440314
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 53
      - 54
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.8.8
      5: 0.13.1
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 50
component:
  desc: null
  value: null
criterion_name:
  desc: null
  value: MSELoss
cutoff_percentile:
  desc: null
  value: null
drop_prob:
  desc: null
  value: 0.3
input_dim:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.0005
model_name:
  desc: null
  value: MC_Dropout_changing_numunits
num_epochs:
  desc: null
  value: 1000
num_layers:
  desc: null
  value: 5
num_samples:
  desc: null
  value: 150
num_units:
  desc: null
  value: 100
ood_lims_in:
  desc: null
  value:
  - - 0.0
    - 3.0
  - - 0.0
    - 3.0
  - - 0.0
    - 3.0
  - - 0.0
    - 5.0
  - - 0.0
    - 5.0
  - - 0.0
    - 5.0
ood_lims_out:
  desc: null
  value:
  - - 10
    - 25
  - - 10
    - 25
  - - 10
    - 30
  - - 10
    - 12
  - - 10
    - 12
  - - 10
    - 12
optimiser_name:
  desc: null
  value: Adam
output_dim:
  desc: null
  value: 4
seed:
  desc: null
  value: 1234
sortby:
  desc: null
  value: null
train_lims_all:
  desc: null
  value:
  - - 3.0
    - 10
  - - 3.0
    - 10
  - - 3.0
    - 10
  - - 5.0
    - 10
  - - 5.0
    - 10
  - - 5.0
    - 10
val_split:
  desc: null
  value: null
weight_decay:
  desc: null
  value: null
x_cols:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
y_cols:
  desc: null
  value:
  - 6
  - 7
  - 8
  - 9
