name: pytest_Ubuntu
on:
  push:


jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Install Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    # Install dependencies 
    - run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        
    # Run tests
    - name: Test with pytest
      run: |
        pytest tests/tests.py
